

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalProfile from './components/GlobalProfile'

import { trackUserActivity } from '../app/utils/activityTracker';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import ComProfile from './components/CompProfile';
import NavBar from './NavBar'
import { Providers } from './providers'
import { type ReactNode } from 'react'

export default function RootLayout(props: { children: ReactNode }) {

  function trackActivity(activity: string) {
    trackUserActivity(activity);
  }
  // useEffect(() => {
  //   // Example: Track page load activity
  //   trackActivity('Page loaded');
  // }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
 
        <Providers>
           <NavBar></NavBar>
           {props.children}
        </Providers>
        </body>
    </html>
  )
}


/*
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
 
        
        <Providers>
        <NavBar></NavBar>
        <GlobalProfile/>
          {props.children}</Providers>
        </body>
    </html>
  )
}
*/


