
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { WagmiConfig, useAccount } from 'wagmi'
import ComProfile from './components/CompProfile';
import { chains, publicClient, webSocketPublicClient } from './components/wrapperForWagmi';
import { InjectedConnector } from 'wagmi/connectors/injected';

import { createConfig, Config } from 'wagmi'
import { WagmiConfigProvider } from './components/WagmiConfigProvider';
import { MetaMaskConnector } from 'wagmi/connectors/metaMask'
import NavBar from './NavBar'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

//   const metaMaskConnector = new MetaMaskConnector({
//     chains,
//     options: {
//       shimDisconnect: false,
//     },

//   })

//   const injectedConnector = new InjectedConnector({
//     chains,
//     options: {
//         name: 'Injected',
//         shimDisconnect: true,
//     }
// });
//   const wagmiConfig1 = createConfig({
//     autoConnect: true,
//     publicClient,
//     connectors: [metaMaskConnector
        
//     ],
//     webSocketPublicClient,
// })

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <WagmiConfig config = {wagmiConfig1}>  
              <ComProfile/>
        </WagmiConfig> */}
        <NavBar></NavBar>
          <main>
          {/* <WagmiConfig config = {wagmiConfig1}>  
              <ComProfile/>
              {children}  
          </WagmiConfig> */}
          
            {children} 
         

          </main>
        </body>
    </html>
  )
}
